#define SERVO_LEFT_FRONT_1 		16  //servo 16
#define SERVO_LEFT_FRONT_2		17  //servo 17
#define SERVO_LEFT_FRONT_3		18  //servo 18
#define SERVO_LEFT_CENTER_1		20	//servo 20
#define SERVO_LEFT_CENTER_2 	21	//servo 21
#define SERVO_LEFT_CENTER_3		22	//servo 22
#define SERVO_LEFT_REAR_1			24	//servo 24
#define SERVO_LEFT_REAR_2			25	//servo 25
#define SERVO_LEFT_REAR_3			26	//servo 26

#define SERVO_RIGHT_FRONT_1 	0		//servo 0
#define SERVO_RIGHT_FRONT_2 	1		//servo 1
#define SERVO_RIGHT_FRONT_3 	2		//servo 2
#define SERVO_RIGHT_CENTER_1 	4		//servo 4
#define SERVO_RIGHT_CENTER_2 	5		//servo 5
#define SERVO_RIGHT_CENTER_3 	6		//servo 6
#define SERVO_RIGHT_REAR_1  	8		//servo 8
#define SERVO_RIGHT_REAR_2 		9		//servo 9
#define SERVO_RIGHT_REAR_3 		10	//servo 10

#define SERVO_LEFT_MANDIBLE   28	//servo 28
#define SERVO_RIGHT_MANDIBLE  12	//servo 12
#define SERVO_NECK_VERTICAL   29	//servo 29
#define SERVO_NECK_HORIZONTAL 13	//servo 13
#define SERVO_NECK_BALANCE	  14	//servo 14

#define PULSEWIDTH_HORIZONTAL_LEFT_REAR_H			6			// 1700
#define PULSEWIDTH_HORIZONTAL_LEFT_REAR_L			164
#define PULSEWIDTH_HORIZONTAL_LEFT_CENTER_H 	5			// 1500
#define PULSEWIDTH_HORIZONTAL_LEFT_CENTER_L 	220
#define PULSEWIDTH_HORIZONTAL_LEFT_FRONT_H		5			// 1300
#define PULSEWIDTH_HORIZONTAL_LEFT_FRONT_L		20

#define PULSEWIDTH_HORIZONTAL_RIGHT_REAR_H		5			//1300
#define PULSEWIDTH_HORIZONTAL_RIGHT_REAR_L		20
#define PULSEWIDTH_HORIZONTAL_RIGHT_CENTER_H	5			//1500
#define PULSEWIDTH_HORIZONTAL_RIGHT_CENTER_L	220
#define PULSEWIDTH_HORIZONTAL_RIGHT_FRONT_H		6			//1700
#define PULSEWIDTH_HORIZONTAL_RIGHT_FRONT_L		164

#define PULSEWIDTH_VERTICAL_LEFT_LOW_H				7			//1800
#define PULSEWIDTH_VERTICAL_LEFT_LOW_L				8
#define PULSEWIDTH_VERTICAL_LEFT_MID_H				5			//1500
#define PULSEWIDTH_VERTICAL_LEFT_MID_L				220
#define PULSEWIDTH_VERTICAL_LEFT_HIGH_H				4			//1200
#define PULSEWIDTH_VERTICAL_LEFT_HIGH_L				176

#define PULSEWIDTH_VERTICAL_RIGHT_LOW_H				4			//1200
#define PULSEWIDTH_VERTICAL_RIGHT_LOW_L				176
#define PULSEWIDTH_VERTICAL_RIGHT_MID_H				5			//1500
#define PULSEWIDTH_VERTICAL_RIGHT_MID_L				220
#define PULSEWIDTH_VERTICAL_RIGHT_HIGH_H			7			//1800
#define PULSEWIDTH_VERTICAL_RIGHT_HIGH_L			8

#define PULSE_SIGN						80    // PULSEWIDTH P
#define SHARP_SIGN 						35		//# sign
#define EXECUTION_TIME 				84		// execution time T
#define START_PAUSE						83   	// START or PAUSE S
